# Generated by Django 4.1.4 on 2022-12-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
