# Generated by Django 4.1.4 on 2022-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Domains',
            field=models.IntegerField(default=0),
        ),
    ]
