# Generated by Django 4.1.4 on 2022-12-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_customer_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain_Name', models.CharField(max_length=50)),
                ('Purchase_Date', models.DateField()),
                ('Renewal_Date', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField(default=100)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.customer')),
            ],
        ),
    ]
